# -*- coding: utf-8 -*-
"""Titanic_Capstone_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13opfvfCytkFow0rmQvkhqLyzRZSoUrty

# **Titanic Data Cleaning and Analysis Project**

**Dataset:** Titanic Passenger Dataset

**Objective:**
The goal of this project is to clean and prepare the Titanic dataset using Python and Pandas. The cleaned dataset will later be used in Power BI to create visualizations and gain insights about passenger survival patterns.

# **1. Import Required Dataset and Libraries**

I imported the required dataset and the libraries needed for data manipulation and numerical operations.
"""

from google.colab import files
uploaded = files.upload()

# Import pandas for data analysis and manipulation
import pandas as pd

# Import numpy for numerical operations and handling missing values
import numpy as np

"""# **2. Load the Dataset**

The dataset is loaded into a pandas DataFrame so that i can explore and clean it.
"""

# Load the Titanic dataset into a DataFrame
df = pd.read_csv("titanic.csv")

# Display the first 5 rows of the dataset
df.head()

"""# **3. Explore the Dataset**

Before cleaning the data, it is important to understand its structure, data types, and potential issues.
"""

# Display summary information about the dataset
# This includes column names, data types, and number of non-null values
df.info()

# To check for missing values in each column
df.isnull().sum()

# To check if there are duplicate rows in the dataset
df.duplicated().sum()

"""# **4. Column Standardization**

I standardized the column names by converting them to lowercase and removing extra spaces. I did this to avoid errors when calling the columns in my analysis since the original dataset had mixed capitalization. This helps me maintain consistency while working with the dataset.
"""

# Convert all column names to lowercase and remove extra spaces
df.columns = df.columns.str.lower().str.strip()

# This shows if all columns are converted to lowercase and extra spaces removed.
df.columns

"""# **5. Replace Non-Standard Missing Values**

In this dataset, some missing values are represented as \N instead of NaN.
These must be replaced with proper NaN values so pandas can detect them.
"""

df['age'].dtype

df.columns

import numpy as np
df['age'] = df['age'].replace('\\N', np.nan)

df.isnull().sum()

"""# **6. Clean the Age Column**

The Age column contains missing values and must be converted to numeric format before filling missing values.
"""

# Convert the Age column to numeric values
# Any invalid entries will be converted to NaN
df['age'] = pd.to_numeric(df['age'], errors='coerce')

# Fill missing Age values using the median age
# Median is preferred because it is less affected by outliers
df['age'] = df['age'].fillna(df['age'].median())

# To check if missing values are still present
df['age'].isnull().sum()

df.isnull().sum()

"""# **7. Handle Cabin Column**

The Cabin column contains a large number of missing values.
Instead of filling them, we create a new column indicating whether a passenger had a cabin.
"""

# Check if Cabin column exists before using it
if 'cabin' in df.columns:

    # Create a binary column: 1 if passenger had a cabin, 0 if not
    df['has_cabin'] = df['cabin'].notnull().astype(int)

    # Drop the original Cabin column because it has too many missing values
    df.drop(columns=['cabin'], inplace=True)

df.columns

df.isnull().sum()

"""# **8. Handle Embarked Column**

The Embarked column has a small number of missing values.
I replace them with the most frequent value (mode).
"""

# Fill missing values in Embarked column using the most common value
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

df.isnull().sum()

"""# **9. Feature Engineering**

Feature engineering involves creating new useful variables from existing data.

**Create Family Size Feature**

This feature represents the total number of family members traveling together.
"""

# Create a new column representing total family size
# It includes the passenger plus siblings/spouses and parents/children
df['family_size'] = df['sibsp'] + df['parch'] + 1

# To check if the new family_size column was calculated correctly.
df[['sibsp','parch','family_size']].head()

"""**Create Age Group Feature**

Passengers are categorized into age groups for easier analysis.
"""

# Define a function to categorize passengers into age groups
def age_group(age):
    if age < 13:
        return "Child"
    elif age < 20:
        return "Teen"
    elif age < 60:
        return "Adult"
    else:
        return "Senior"

# Apply the function to create a new age_group column
df['age_group'] = df['age'].apply(age_group)

# Display the first rows of age and age_group to confirm it worked
df[['age','age_group']].head()

"""**Extract Passenger Title**

Passenger titles such as Mr, Mrs, and Miss can provide additional insights
"""

df['title'] = df['name'].str.extract(r' ([A-Za-z]+)\.', expand=False)

# To check if the titles were extracted.
df[['name','title']].head()

"""# **10. Remove Duplicate Rows**

I removed the duplicates because it can affect analysis and should be removed.
"""

df.drop_duplicates(inplace=True)

# To check if the duplicates were removed.
df.columns

"""# **11. Save Cleaned Dataset**

The cleaned dataset is exported as a CSV file to be used in Power BI for visualization.
"""

# Save the cleaned dataset as a CSV file
df.to_csv("titanic_cleaned.csv", index=False, na_rep="")


# Download dataset
from google.colab import files
files.download("titanic_cleaned.csv")
